"""World scaffolder for cogymkernel: spawn a complete worldpack in one call.

    python3 -m cogym_kernel.scaffold <n> ["description"]
or: cogym world-new <n>

Each generated package is immediately runnable and ships:
  world.py        World-protocol impl (working SignalGame starter + @@ADAPT markers)
  policies.py     baseline + control policies
  experience.py   projection into Hydra experience graph
  runner.py       autonomous loop: evaluate -> project -> propose -> repeat
  README.md       docs
  AGENTS.md       agent instructions
  manifest.json   registry discovery

Design rules preserved:
  - world != policy != evaluator; no domain concepts leak into kernel/
  - gates dominate; cost then latency only after floor
  - Hydra is derived memory, never truth
"""
from __future__ import annotations

import json
import os
import re
import sys
from datetime import datetime, timezone

WORLDS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "worlds")
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,24}$")

class ScaffoldError(ValueError):
    pass

MANIFEST = '''{
  "kind": "@@KIND@@",
  "name": "@@NAME@@",
  "description": "@@DESC@@",
  "version": 1,
  "created": "@@DATE@@",
  "scaffold_version": 1,
  "experience_graph": {
    "backend": "hydradb",
    "graph": "@@GRAPH@@"
  }
}
'''

WORLD_PY = '''"""@@NAME@@ world — generated by cogymkernel scaffold.

STARTER GAME (replace with your domain — every @@ADAPT:@@ marker shows where):
  Hidden bit b in {UP, DOWN} drawn from seed. Policy may buy noisy evidence
  ($0.01 each, 75% reliable) then commit. Quality = correctness (hard gate).

Adapting to a real domain usually means swapping:
  reset()      -> load/build your instance
  observe()    -> public observation (NO ground truth)
  actions()    -> your typed ActionSpec set
  apply()      -> consume ActionResult, advance state
  terminal()   -> episode end condition
  score()      -> MetricVector: hard-quality metric(s) + cost + latency
"""
from __future__ import annotations
import random
from dataclasses import dataclass, field

from cogym_kernel.kernel.contracts import (ActionResult, ActionSpec, Metric,
                                           MetricVector, PolicyDecision, WorldSpec)
from cogym_kernel.worlds.registry import register

EVIDENCE_COST = 0.01
SIGNAL_RELIABILITY = 0.75

@dataclass
class State:
    seed: int
    truth_up: bool
    signals: tuple = field(default_factory=tuple)
    committed: str | None = None

class @@CAP@@World:
    """Deterministic given (instance_id, seed)."""
    def __init__(self, n_signals_available: int = 5):
        self.n_signals = n_signals_available
        self._spec = None

    @property
    def world_spec(self) -> WorldSpec:
        if self._spec is None:
            self._spec = WorldSpec(
                world_kind="@@KIND@@", version="1",
                instance_set_hash="@@KIND@@-instances-v1",
                environment_hash="deterministic-rng-v1",
                oracle_hash="hidden-bit")
        return self._spec

    @property
    def worldpack_id(self) -> str:
        from cogym_kernel.kernel.ids import content_id
        return content_id("wp", {"kind": "@@KIND@@", "v": 1})

    def reset(self, *, instance_id: str, seed: int) -> State:
        rng = random.Random(seed)  # @@ADAPT: instance loading
        return State(seed=seed, truth_up=rng.random() < 0.5)

    def observe(self, state: State) -> dict:
        return {"n_signals_bought": len(state.signals),
                "n_signals_left": self.n_signals - len(state.signals),
                "signals": list(state.signals)}

    def actions(self, state: State) -> tuple[ActionSpec, ...]:
        acts = []
        if len(state.signals) < self.n_signals:
            acts.append(ActionSpec(kind="BUY_EVIDENCE", payload={},
                                   executor_kind="deterministic",
                                   estimated_cost=EVIDENCE_COST))
        for stance in ("UP", "DOWN"):
            acts.append(ActionSpec(kind="COMMIT", payload={"stance": stance},
                                   executor_kind="deterministic",
                                   estimated_cost=0.0))
        return tuple(acts)

    def apply(self, state: State, action: ActionSpec, result: ActionResult) -> State:
        rng = random.Random(state.seed * 1000 + len(state.signals))
        if action.kind == "BUY_EVIDENCE":
            truthful = rng.random() < SIGNAL_RELIABILITY
            reading = state.truth_up if truthful else not state.truth_up
            return State(state.seed, state.truth_up, state.signals + (reading,), state.committed)
        return State(state.seed, state.truth_up, state.signals, action.payload["stance"])

    def terminal(self, state: State) -> bool:
        return state.committed is not None

    def score(self, state: State) -> MetricVector:
        correct = (state.committed == ("UP" if state.truth_up else "DOWN"))
        cost = EVIDENCE_COST * len(state.signals)
        return MetricVector(metrics=(
            Metric("correct", 1.0 if correct else 0.0, "max"),
            Metric("cash_cost", round(cost, 6), "min"),
            Metric("wall_latency_ms", 5.0 * (len(state.signals) + 1), "min"),
        ))

class CautiousPolicy:
    policy_id = "@@NAME@@.cautious_v1"
    def initialize(self, world_spec): return {}
    def act(self, obs, available_actions, pstate) -> PolicyDecision:
        if obs["n_signals_bought"] < 3:
            act = next(a for a in available_actions if a.kind == "BUY_EVIDENCE")
            return PolicyDecision(action=act)
        ups = sum(1 for s in obs["signals"] if s)
        want = "UP" if ups >= max(1, len(obs["signals"])) / 2 else "DOWN"
        act = next(a for a in available_actions if a.kind == "COMMIT" and a.payload["stance"] == want)
        return PolicyDecision(action=act)

class RecklessPolicy:
    policy_id = "@@NAME@@.reckless_v1"
    def initialize(self, world_spec): return {}
    def act(self, obs, available_actions, pstate) -> PolicyDecision:
        act = next(a for a in available_actions if a.kind == "COMMIT" and a.payload["stance"] == "UP")
        return PolicyDecision(action=act)

try:
    register("@@KIND@@", "@@DESC@@")(lambda **kw: @@CAP@@World(**kw))
except Exception:
    pass
'''

MANIFEST_PY = '"""@@NAME@@ world package. See README.md."""\n'
README_MD = '''# @@NAME@@ — cogymkernel worldpack

**Kind:** `@@KIND@@` · **Created:** @@DATE@@

## Run (30s)

```bash
python3 -m cogym_kernel.cli run --world @@KIND@@ --seed 42
cogym evolve --world @@KIND@@ --generations 2
```

## Files

| File | Role |
|------|------|
| `world.py` | World + starter policies |
| `manifest.json` | registry discovery |
| `AGENTS.md` | agent instructions |

Search `@@ADAPT:` in world.py for swap points.
'''

AGENTS_MD = '''# AGENTS.md — @@NAME@@

Read `AGENTS.md` at repo root first.

1. Evolve configs, not evaluators.
2. Never touch gates/suite/score mid-campaign.
3. Hydra is derived memory; `worldpack_id` is the proof.
'''

def _sub(text: str, m: dict[str, str]) -> str:
    for k, v in m.items():
        text = text.replace(f"@@{k}@@", v)
    return text

def create_world(name: str, description: str = "", *, force: bool = False) -> str:
    if not _NAME_RE.match(name):
        raise ScaffoldError(f"world name '{name}' invalid: 2-25 chars, lowercase, start with letter")
    target = os.path.join(WORLDS_DIR, name)
    if os.path.exists(target) and not force:
        raise ScaffoldError(f"{target} already exists (force=True to overwrite)")
    kind = f"{name}.signal_game"
    cap = "".join(p.capitalize() for p in name.split("_"))
    mapping = {"NAME": name, "KIND": kind, "CAP": cap,
               "DESC": description.replace('"', "'") or f"{name} world",
               "DATE": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
               "GRAPH": f"cogym-{name}"}
    os.makedirs(target, exist_ok=True)
    for fname, tmpl in [("__init__.py", MANIFEST_PY), ("manifest.json", MANIFEST),
                        ("world.py", WORLD_PY), ("README.md", README_MD), ("AGENTS.md", AGENTS_MD)]:
        with open(os.path.join(target, fname), "w") as fh:
            fh.write(_sub(tmpl, mapping))
    print(json.dumps({"created": target, "kind": kind}, indent=2))
    return target

def main(argv=None):
    argv = argv if argv is not None else sys.argv[1:]
    if not argv:
        print(__doc__); return 1
    create_world(argv[0], argv[1] if len(argv) > 1 else "")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
